--- 
- hosts: web
  become: True
  tasks: 
    - name: Installing package
      apt: 
        name: apache2
        state: present
    - name: Start Apache server
      service:
        name: apache2 
        state: start 
        enabled: True
    - name: deploy static website
      copy: 
        src: index.html
        dest: /var/www/html/
