--- 
- 
  become: true
  hosts: web
  tasks: 
    - 
      name: "Installing package"
      yum: 
        name: httpd
        state: present
    - 
      name: "Start Apache server"
      service: "name:httpd state:started enabled:True"
    - 
      copy: 
        dest: /var/www/html/
        src: index.html
      name: "deploy static website"
